version: 2

project_name: rulepack

before:
  hooks:
    - go mod tidy

builds:
  - id: rulepack
    main: ./cmd/rulepack
    binary: rulepack
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: git

nfpms:
  - id: deb
    package_name: rulepack
    description: Compose instruction modules from Git-based rule packs.
    homepage: https://github.com/alexgornovoi/rule-pack
    maintainer: Alex <alex@example.com>
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

homebrew_casks:
  - name: rulepack
    repository:
      owner: alexgornovoi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/alexgornovoi/rule-pack
    description: Compose instruction modules from Git-based rule packs.
    url:
      verified: github.com/alexgornovoi/rule-pack
